### ISSUE TITLE
Could i ask you something?

### ISSUE THREAD

**Issue by GreenD93** [amanwalia92/KeyFramesExtraction#5]
Why do you use the difference in LUV colorspace?, not considering others spaces(RGB, HSV so on...)

**Comment by amanwalia123** [comment]
The choice of LUV colorspace is mainly due to how it differentiates illuminance from chromaticity which will not be available in RGB colorspace.
Another main reason better explained under this[ link ](https://photo.stackexchange.com/questions/67933/when-to-use-luv-and-not-rgb-colourspaces) is as follows: 

> **More specifically 'Luv' was designed to be 'perceptually linear'. That is that a small change in color in one part of the colorspace looks to be about the same, as a similar change in another part of the colorspace. This makes LUV colorspace much better suited for image difference comparisons.**

**Comment by GreenD93** [comment]
Thank you very much!
