### ISSUE TITLE
how to select parameter  window_len?

### ISSUE THREAD

**Issue by zHaOshuAnGye** [amanwalia92/KeyFramesExtraction#8]
hello, nice project ! Its very useful.
But I have a question : Since 'window_len' parameters have a great influence on the experimental results, how to choose the right window_len. Can you give some advice? Thank you very much.

**Comment by amanwalia123** [comment]
Since `window_len` control the extent of smoothness in frame variation, you should give it a high value when there are too many local maximas (e.g. video is choppy or have sudden variations). The actual value is subjective to the kind of videos you are passing as input. You should also look at the generated graph to decide about optimal value for `window_len`.
